### ISSUE TITLE
have you tested?

### ISSUE THREAD

**Issue by k4m4h4l** [Marcosgcr/ArbitragemNano#2]
Do you have any results to show?

**Comment by Marcosgcr** [comment]
No, i didn't tested so far.

**Comment by Marcosgcr** [comment]
In the following days I will test it, but since it needs a momentum I can´t predict if I will succeed. 
If not, the problem may not be the code.

The difference between Kraken and Binance of NANO(XNO) needs to be greater to pay for the fees and have a bit of profit. Soo, testing is a combination of the sucess of the code and the momentum of the difference between Binance and Kraken and exchange fees.

Thanks for the comment though.

**Comment by Marcosgcr** [comment]
Yes, i tested. It is needed a lot of volume to get profit.
